<header>
ようこそ、ゲストさん<br>
<!-- Todo:ゲスト部分の出し分け(未ログイン：ゲスト表示 / ログイン済み：ユーザ名表示)-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- logo 省略
<a href="/var/www/html/index.html"><img src="http://www.organic-kitchen.co.jp/rogo%20BK.gif" alt="LOGO" width="250" height="100"><br>
-->
旬のお野菜たっぷりのお弁当<br>

<nav>
	<a href="https://www.facebook.com/organic.kitchen.2009">Facebook</a></li>
	<a href="http://ameblo.jp/organic-kitchen">アメブロ</a></li>

	<a href="/html/company.html">企業情報</a></li>
	<a href="/html/user/login.html">ログイン</a></li>
<!--
	or 
	<a href="/html/user/reg.html">新規登録</a></li>
-->
	<!-- Todo:ゲスト部分の出し分け(未ログイン：ログイン or 新規登録 / ログイン済み：ログアウト)-->
</nav>
<hr>
</header>
<!-- 以下、body -->
